name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 14 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has been automatically marked as stale because it has not had activity in the last 30 days. Remove stale label or comment or this will be closed in 5 days. Thank you for your contributions.'
        days-before-stale: 30
        days-before-close: 5
        stale-issue-label: 'no-issue-activity'
